# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trafficSystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, _mainWindow):
        _mainWindow.setObjectName("MainWindow")
        _mainWindow.resize(767, 579)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(_mainWindow.sizePolicy().hasHeightForWidth())
        _mainWindow.setSizePolicy(sizePolicy)

        self.centralwidget = QtWidgets.QWidget(_mainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.ImageBox = QtWidgets.QGraphicsView(self.centralwidget)
        self.ImageBox.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.ImageBox.setObjectName("ImageBox")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(660, 250, 95, 126))
        self.widget.setObjectName("widget")

        self.buttonsLayout = QtWidgets.QVBoxLayout(self.widget)
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setSpacing(20)
        self.buttonsLayout.setObjectName("verticalLayout")

        self.CameraButton = QtWidgets.QPushButton(self.widget)
        self.CameraButton.setObjectName("CameraButton")
        self.buttonsLayout.addWidget(self.CameraButton)

        self.VideoButtion = QtWidgets.QPushButton(self.widget)
        self.VideoButtion.setObjectName("VideoButtion")
        self.buttonsLayout.addWidget(self.VideoButtion)

        self.FileButton = QtWidgets.QPushButton(self.widget)
        self.FileButton.setObjectName("FileButton")
        self.buttonsLayout.addWidget(self.FileButton)

        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(440, 500, 158, 24))
        self.widget1.setObjectName("widget1")

        self.FPS_StatusLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.FPS_StatusLayout.setContentsMargins(0, 0, 0, 0)
        self.FPS_StatusLayout.setSpacing(30)
        self.FPS_StatusLayout.setObjectName("horizontalLayout")

        self.FPSSwitch = QtWidgets.QRadioButton(self.widget1)
        self.FPSSwitch.setObjectName("FPSSwitch")
        self.FPS_StatusLayout.addWidget(self.FPSSwitch)

        self.FPSTextLabel = QtWidgets.QLabel(self.widget1)
        self.FPSTextLabel.setObjectName("FPSTextLabel")
        self.FPS_StatusLayout.addWidget(self.FPSTextLabel)

        _mainWindow.setCentralWidget(self.centralwidget)

        # self.menubar = QtWidgets.QMenuBar(_mainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 26))
        # self.menubar.setObjectName("menubar")
        # _mainWindow.setMenuBar(self.menubar)

        self.retranslateUi(_mainWindow)
        QtCore.QMetaObject.connectSlotsByName(_mainWindow)

    def retranslateUi(self, _mainWindow):
        _translate = QtCore.QCoreApplication.translate

        _mainWindow.setWindowTitle(_translate("MainWindow", "交通路况检测系统"))
        self.CameraButton.setText(_translate("MainWindow", "摄像头"))
        self.VideoButtion.setText(_translate("MainWindow", "视频"))
        self.FileButton.setText(_translate("MainWindow", "文件"))
        self.FPSSwitch.setText(_translate("MainWindow", "FPS监测"))
        self.FPSTextLabel.setText(_translate("MainWindow", "FPS:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
